"""add_department_id_to_invitations

Revision ID: 14e90742db5f
Revises: 773982f996b3
Create Date: 2026-05-14 03:00:27.993848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '14e90742db5f'
down_revision: Union[str, None] = '773982f996b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('department_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'invitations', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.drop_column('invitations', 'department_id')
    # ### end Alembic commands ###