"""add is_active to users

Revision ID: 7a8eb238eec4
Revises: fb18fe76bd1e
Create Date: 2026-05-04 10:59:13.689032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7a8eb238eec4'
down_revision: Union[str, None] = 'fb18fe76bd1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###