"""create_onboarding_templates_and_template_tasks

Revision ID: faeca880dc24
Revises: c3466e23b228
Create Date: 2026-05-11 03:55:57.628416

"""
from collections.abc import Sequence

revision: str = 'faeca880dc24'
down_revision: str | None = 'c3466e23b228'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###