"""create_onboarding_templates_and_template_tasks

Revision ID: faeca880dc24
Revises: c3466e23b228
Create Date: 2026-05-11 03:55:57.628416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'faeca880dc24'
down_revision: Union[str, None] = 'c3466e23b228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###