"""create refresh tokens table

Revision ID: fb18fe76bd1e
Revises: d95c8773bd6d
Create Date: 2026-05-04 09:21:28.096978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fb18fe76bd1e'
down_revision: Union[str, None] = 'd95c8773bd6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###