export const API = {
  INVITATIONS: {
    VALIDATE: '/api/v1/invitations/validate',
    CREATE: '/api/v1/invitations',
    LIST: '/api/v1/invitations',
    RESEND: (id: string) => `/api/v1/invitations/${id}/resend`,
  },
  AUTH: {
    REGISTER: '/api/v1/auth/register',
    LOGIN: '/api/v1/auth/login',
    REFRESH: '/api/v1/auth/refresh',
    LOGOUT: '/api/v1/auth/logout',
  },
  USERS: {
    ME: '/api/v1/users/me',
    UPDATE_ME: '/api/v1/users/me',
    LIST: '/api/v1/users/',
    UPDATE: (id: string) => `/api/v1/users/${id}`,
    DEACTIVATE: (id: string) => `/api/v1/users/${id}/deactivate`,
  },
  DEPARTMENTS: {
    LIST: '/api/v1/departments/',
    CREATE: '/api/v1/departments/',
    UPDATE: (id: string) => `/api/v1/departments/${id}`,
    DEACTIVATE: (id: string) => `/api/v1/departments/${id}/deactivate`,
    REACTIVATE: (id: string) => `/api/v1/departments/${id}/reactivate`,
  },
  TEMPLATES: {
    LIST: '/api/v1/templates/',
    CREATE: '/api/v1/templates/',
    UPDATE: (id: string) => `/api/v1/templates/${id}`,
    ACTIVATE: (id: string) => `/api/v1/templates/${id}/activate`,
    DEACTIVATE: (id: string) => `/api/v1/templates/${id}/deactivate`,
    CLONE: (id: string) => `/api/v1/templates/${id}/clone`,
    GET_TASKS: (id: string) => `/api/v1/templates/${id}/tasks`,
    ADD_TASK: (id: string) => `/api/v1/templates/${id}/tasks`,
    UPDATE_TASK: (id: string, taskId: string) => `/api/v1/templates/${id}/tasks/${taskId}`,
    DELETE_TASK: (id: string, taskId: string) => `/api/v1/templates/${id}/tasks/${taskId}`,
    REORDER_TASK: (id: string, taskId: string) => `/api/v1/templates/${id}/tasks/${taskId}/reorder`,
  },
}
